### ISSUE TITLE
Parse Error?

### ISSUE THREAD

**Issue by kishiyamat** [uncaneton/jsPsych_exp_test#1]
https://github.com/uncaneton/jsPsych_exp_test/blob/3704e5b3542f3d20beea366b1af4559749c6ccd5/prac_session_test#L103

```js
          if(data.button_pressed == trial_num2[i]].button){
```
は
```js
          if(data.button_pressed == trial_num2[i].button){
```

ですかね

**Comment by uncaneton** [comment]
確かに。直しました！

**Comment by kishiyamat** [comment]
たぶんこれで何やっても false になったんでしょうね

**Comment by uncaneton** [comment]
何やってもfalseだった...

**Comment by kishiyamat** [comment]
なおりました？

**Comment by uncaneton** [comment]
同じくやってもfalseだったんだよね。 `data.button_pressed == trial_num2[i].button` これはちゃんと上のpropertyをレフェリングしてるのかな....

**Comment by kishiyamat** [comment]
てもとだとうまくいきますけど

**Comment by uncaneton** [comment]
https://hel8zyaxub.cognition.run

**Comment by kishiyamat** [comment]
https://lbyskcliuh.cognition.run/

**Comment by uncaneton** [comment]
あっ

**Comment by kishiyamat** [comment]
なんか色々きえてますね

**Comment by uncaneton** [comment]
きっしーを自分のスクリプトの編集者に入れてもいい？

**Comment by kishiyamat** [comment]
```js
          if(data.button_pressed == data.button){
```
ではなく
```js
          if(data.button_pressed == trial_num2[i].button){

```

**Comment by kishiyamat** [comment]
いいですよ！

**Comment by uncaneton** [comment]
ありがとう。使ってるメールアドレスを教えてもらっていいかな

**Comment by kishiyamat** [comment]
https://github.com/uncaneton/jsPsych_exp_test/pull/2

**Comment by kishiyamat** [comment]
これをマージして、コピペすればなおりますよ

**Comment by kishiyamat** [comment]
差分は https://github.com/uncaneton/jsPsych_exp_test/pull/2/files で見れます

**Comment by kishiyamat** [comment]
ちなみにメアドは kishiyama.t@gmail.com です

**Comment by uncaneton** [comment]
やってみます！

**Comment by uncaneton** [comment]
なんでだめなのかな...　#2 は修正してあるはずなのに

**Comment by kishiyamat** [comment]
あれ音流れなくないですか？

**Comment by kishiyamat** [comment]
いやながれますね

**Comment by uncaneton** [comment]
true出てくる？

**Comment by kishiyamat** [comment]
でてきません。ちょっと僕のと差分とってみます

**Comment by kishiyamat** [comment]
差分ないですね、修正できてます

**Comment by uncaneton** [comment]
プレビューの問題かとも思ってたが、やっぱり実際リンクからやってもtrueが出てこないね....
きっしーのスクリプトは全然問題なくtrue/falseの判断ができてるけど

**Comment by kishiyamat** [comment]
なぜ...

**Comment by uncaneton** [comment]
おれはJsPsychに嫌われているのか！？
いや、でもこれでもう二週間悩んでいた😢
この先、三問連続で正解しないとloop!というのもまだできてないし...

**Comment by kishiyamat** [comment]
15分なやんでダメだったら相談してください！

**Comment by kishiyamat** [comment]
あとはキャッシュくらいですかね

**Comment by kishiyamat** [comment]
違いますね

**Comment by kishiyamat** [comment]
考えづらいですがファイルの置き場所ですかね？

**Comment by kishiyamat** [comment]
```
20c20
<   stimulus: "pianolong.wav",
---
>   stimulus: "sound/pianolong.wav",
48c48
<   stimulus: 'aa261.wav',
---
>   stimulus: 'sound/aa261.wav',
53c53
<   stimulus: 'ax263.wav',
---
>   stimulus: 'sound/ax263.wav',
58c58
<   stimulus: 'ax264.wav',
---
>   stimulus: 'sound/ax264.wav',
63c63
<   stimulus: 'ax265.wav',
---
>   stimulus: 'sound/ax265.wav',
68c68
<   stimulus: 'ax276.wav',
---
>   stimulus: 'sound/ax276.wav',
```

**Comment by kishiyamat** [comment]
僕は勝手にダウンロードした音源を直に置いてるんですが、もとのスクリプトでは sound下においていて、それくらいしか差が無いです

**Comment by kishiyamat** [comment]
ただ、音源は読み込めてるのでこの線は薄いんですよね...

**Comment by kishiyamat** [comment]
シークレットモードでもバグってるので、以前回答したキャッシュが残ってバグってる線もありませんよね

**Comment by uncaneton** [comment]
あの.............
この問題は解決したと思われた兆候が出てきたが、理由がばかばかしすぎてちょっとjsPsychに怒っている

**Comment by kishiyamat** [comment]
なんだったんですか？

**Comment by uncaneton** [comment]
左上のバージョンだね.........
二週間前に書いたときは6.2だったんで、今もそれを継いでるけど
6.3にしたらなおった

**Comment by kishiyamat** [comment]
＿人人人人人人人人＿
＞　なんでやねん　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^￣

**Comment by uncaneton** [comment]
6.2にしたら死亡

**Comment by kishiyamat** [comment]
なおってよかったです

**Comment by uncaneton** [comment]
うわーありがとう.............................

**Comment by kishiyamat** [comment]
他にも変なところあったら相談してください！

**Comment by uncaneton** [comment]
そもそもきっしーがいなければその謎の]もなおってなかったので感謝感謝

**Comment by uncaneton** [comment]
いや、今の、trueしかでてこないことがわかった。6.2版はfalseばっかで6.3はtrueになる。

**Comment by kishiyamat** [comment]
ひえ

**Comment by kishiyamat** [comment]
イテレーションのiが変ですね。ちょっとためしてみます

```
for (var i in trial_num2){
```

**Comment by kishiyamat** [comment]
何件か更新しました。手元ではこれで動いてます。

**Comment by kishiyamat** [comment]
https://github.com/uncaneton/jsPsych_exp_test/pull/3

**Comment by uncaneton** [comment]
動くようになった(´；ω；`)ｳｯ… 本当にありがとう！
const of などちょっと勉強してきます。また（書き方について）聞くかもしれないがよろしく！
